# Site settings
title: Beth Urban's blog
header-img: img/home-bg.png
email: beth.urban@gmail.com
copyright_name: bethurban
description: > # this means to ignore newlines until "baseurl:"
  A news editor becomes a web developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bethurban
learn_profile: bethurban
email_username: beth.urban@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
